packages:
  - emacs
install:
  - rm -rf $HOME/.emacs.d && ln -s . $HOME/.emacs.d

script:
  - pwd >&2
  - echo $HOME >&2
  - ls >&2
  - cd /home/travis/build/pyr/dot.emacs/ && emacs --batch -q -l init.el
