sudo: false
install:
  - curl -o - http://mirror.team-cymru.org/gnu/emacs/emacs-24.4.tar.gz | tar xvzf -
  - cd emacs-24.4 && ./configure --prefix=/usr/local && make && make install
  - export PATH=/usr/local/bin:$PATH
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python

script:
  - export PATH=/usr/local/bin:$PATH
  - $HOME/.cask/bin/cask install && emacs --batch -q -l init.el
