sudo: false
packages:
  - libxpm4
  - libgif4
  - libxpm-dev
  - libgif-dev
install:
  - curl -o - http://mirror.team-cymru.org/gnu/emacs/emacs-24.4.tar.gz | tar xzf -
  - cd emacs-24.4 && ./configure --prefix=/usr/local --with-xpm=no --with-gif=no > /dev/null && (make > /dev/null || true) && (make install >/dev/null || true)
  - export PATH=/usr/local/bin:$PATH
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python

script:
  - export PATH=/usr/local/bin:$PATH
  - $HOME/.cask/bin/cask install && emacs --batch -q -l init.el
