sudo: required
packages:
  - emacs24
install:
  - sudo add-apt-repository -y ppa:cassou/emacs && sudo apt-get -qq update
  - sudo apt-get remove --purge emacs
  - sudo apt-get -qq -f install && sudo apt-get -qq install emacs24 emacs24-el
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python

script: $HOME/.cask/bin/cask install && emacs24 --batch -q -l init.el
